namespace: monitoring

grafana:
  enabled: true
  adminPassword: "${GRAFANA_PASS}"
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-name: grafana-clb
      service.beta.kubernetes.io/aws-load-balancer-type: classic

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    replicas: 1
    retention: 30d

alertmanager:
  enabled: true
  service:
    type: ClusterIP
  alertmanagerSpec:
    replicas: 1
    configSecret: alertmanager-custom-config

prometheusOperator:
  admissionWebhooks:
    enabled: false

defaultRules:
  create: true
  rules:
    kubeScheduler: false
    kubeControllerManager: false
    kubeProxy: false
    etcd: false

customAlertmanager:
  smtpSmarthost: smtp.gmail.com:587
  smtpFrom: saharr449@gmail.com
  smtpUsername: saharr449@gmail.com
  smtpPassword: 
  smtpRequireTLS: true
  emailTo: saharr449@gmail.com