alertmanager:
  password: "YOUR_PASSWORD_HERE"
  enabled: true
  alertmanagerSpec:
    config:
      global:
        smtp_smarthost: 'smtp.gmail.com:587'
        smtp_from: 'saharr449@gmail.com'
        smtp_auth_username: 'saharr449@gmail.com'
        smtp_auth_password: ''
        smtp_require_tls: true

      route:
        receiver: 'null'
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 12h

        routes:
          - match:
              alertname: FlaskAppPodDown
            receiver: 'email'
            group_wait: 5s
            group_interval: 10s
            repeat_interval: 1h
          - match_re:
              alertname: .*
            receiver: 'null'

      receivers:
        - name: 'email'
          email_configs:
            - to: 'saharr449@gmail.com'
              send_resolved: true
              headers:
                Subject: 'ðŸš¨ Flask App Alert: {{ .GroupLabels.alertname }}'
              html: |
                <h2>{{ .Status | toUpper }}</h2>
                {{ range .Alerts }}
                <p><b>Alert:</b> {{ .Labels.alertname }}</p>
                <p><b>Severity:</b> {{ .Labels.severity }}</p>
                <p><b>Description:</b> {{ .Annotations.description }}</p>
                {{ if .Labels.pod }}
                <p><b>Pod:</b> {{ .Labels.pod }}</p>
                {{ end }}
                <p><b>Namespace:</b> {{ .Labels.namespace }}</p>
                {{ end }}
        - name: 'null'
